### ISSUE TITLE
BiomeJungle bounds error

### ISSUE THREAD

**Issue by Eluinhost** [Eluinhost/ChunkBiomes#7]
```
java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_60]
        at net.minecraft.server.v1_8_R3.BiomeJungle.a(SourceFile:72) ~[spigot_server.jar:git-Spigot-f94fe8f-d27e6d0]
        at net.minecraft.server.v1_8_R3.ChunkProviderGenerate.getChunkAt(SourceFile:473) ~[spigot_server.jar:git-Spigot-f94fe8f-d27e6d0]
        at org.bukkit.craftbukkit.v1_8_R3.generator.NormalChunkGenerator.getChunkAt(NormalChunkGenerator.java:51) ~[spigot_server.jar:git-Spigot-f94fe8f-d27e6d0]
        at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:267) ~[spigot_server.jar:git-Spigot-f94fe8f-d27e6d0]
        at net.minecraft.server.v1_8_R3.Chunk.loadNearby(Chunk.java:993) ~[spigot_server.jar:git-Spigot-f94fe8f-d27e6d0]
        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:77) ~[spigot_server.jar:git-Spigot-f94fe8f-d27e6d0]
        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) ~[spigot_server.jar:git-Spigot-f94fe8f-d27e6d0]
        at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188) ~[spigot_server.jar:git-Spigot-f94fe8f-d27e6d0]
        at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:347) ~[spigot_server.jar:git-Spigot-f94fe8f-d27e6d0]
        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:34) ~[spigot_server.jar:git-Spigot-f94fe8f-d27e6d0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:733) ~[spigot_server.jar:git-Spigot-f94fe8f-d27e6d0]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) ~[spigot_server.jar:git-Spigot-f94fe8f-d27e6d0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) ~[spigot_server.jar:git-Spigot-f94fe8f-d27e6d0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot_server.jar:git-Spigot-f94fe8f-d27e6d0]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
```

Stack trace caused no side effects on Windows, crashes the server on Linux, need to find cause

**Comment by Eluinhost** [comment]
Cause is that BiomeJungle calls Random.nextInt with getHighestY in the chunk. A transparent block is not counted in getHighestY so the chunk crashes when it returns 0. This only seems to cause issues with transparent borders along the edge of a jungle biome
